name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "."

    - name: Invalidate CloudFront cache
      uses: aws-actions/aws-cloudfront-invalidate-cache@v1
      with:
        distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        paths: '/*'
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Send Discord notification
      if: always()
      uses: Ilshidur/action-discord@master
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL_VANILA }}
        message: |
          🚀 **배포 결과**:
          - 상태: ${{ job.status }}
          - 브랜치: `${{ github.ref_name }}`
          - 커밋: `${{ github.event.head_commit.message }}`
          - 작성자: `${{ github.actor }}`
